
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/shoppingcart?createDatabaseIfNotExist=true"
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: create-drop
      format_sql: true

    show-sql: true
  application:
    name: "Shopping Cart Demo"


